/**
 * Blog content registry. All posts are authored long-form (1000+ words)
 * to satisfy AdSense quality requirements.
 */
export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  date: string; // ISO
  readingTime: string;
  excerpt: string;
  /** Markdown-lite paragraphs / headings. Headings start with `## `. */
  body: string;
  related: string[]; // related tool slugs
  tags: string[];
  faqs: { q: string; a: string }[];
}

const p = (...paragraphs: string[]) => paragraphs.join("\n\n");

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "how-to-convert-pdf-to-word-online",
    title: "How to Convert PDF to Word Online (Free, No Sign-up)",
    description: "A step-by-step guide to turning any PDF into an editable Word document right in your browser, with tips for keeping formatting intact.",
    date: "2026-01-12",
    readingTime: "6 min read",
    excerpt: "PDF is a great format for sharing, but a terrible format for editing. Here is the cleanest way to turn a PDF back into a Word document.",
    related: ["pdf-to-word", "word-to-pdf", "edit-pdf"],
    tags: ["PDF", "Word", "Tutorial"],
    body: p(
      "PDF was designed to look the same on every device, which is exactly why it is hard to edit. The moment you need to fix a typo, update a price or translate a paragraph, you wish the file were a Word document instead. The good news is that converting a PDF to Word is now a five-second job that you can do in your browser, with no installation and no sign-up.",
      "## Why convert PDF to Word",
      "There are three common reasons people convert PDFs to Word. The first is editing: you received a contract, a proposal or a CV as a PDF and you need to make changes. The second is reuse: you want to copy a long article into a Google Doc to translate or summarise it. The third is accessibility: Word documents are easier for screen readers to handle than complex PDFs.",
      "## Step-by-step: convert PDF to Word",
      "1. Open the PDF to Word tool on Convertify.\n2. Drag your PDF onto the upload area, or tap to choose a file from your phone.\n3. Wait a few seconds while the page extracts text. The conversion runs locally on your device — your file is not uploaded.\n4. Click the download button to save a .docx file you can open in Microsoft Word, Google Docs, Pages or LibreOffice.",
      "## How to keep the formatting",
      "PDFs come in two flavours: born-digital PDFs that contain real text, and scanned PDFs that contain pictures of text. Born-digital PDFs convert beautifully — paragraphs, headings and most lists survive the round-trip. Scans need OCR (optical character recognition) before any tool can read them, and the result depends heavily on scan quality.",
      "If your output looks empty or full of strange characters, the PDF is almost certainly a scan. Try a dedicated OCR tool first, then come back to convert the result.",
      "## Privacy considerations",
      "Most PDF-to-Word converters upload your file to a server. That is convenient, but it means a copy of your contract or invoice ends up on someone else's computer. Convertify runs entirely in your browser, so your file is never transmitted. You can verify this in the browser developer tools — there is no upload request.",
      "## Tips for a clean conversion",
      "- Remove password protection from the PDF first. The Unlock PDF tool can help.\n- If the PDF is huge, split it into chunks with the Split PDF tool and convert each part.\n- After conversion, open the .docx in Word or Google Docs and clean up extra blank lines before you start editing.\n- For documents with lots of tables, consider exporting tables separately or recreating them in Word.",
      "## When to use Word to PDF instead",
      "Once you have edited the document, you will probably want to send it back as a PDF so it looks the same for the recipient. Convertify's Word to PDF tool does exactly that — and it also runs in your browser.",
      "## Common mistakes to avoid",
      "The biggest mistake is expecting a perfect 1-to-1 copy of complex layouts (multi-column magazines, brochures with overlapping graphics). Conversion is best for text-heavy documents like contracts, reports, CVs and articles. For complex layouts, treat the conversion as a starting point and tidy up by hand.",
      "## Wrap-up",
      "Converting PDF to Word used to mean paying for Adobe Acrobat or trusting a sketchy upload site. Today, your browser already has all the technology needed to do the job locally — Convertify just packages it into a single page. Bookmark the tool, and you will never need to fight with a locked PDF again.",
    ),
    faqs: [
      { q: "Is the converted Word file editable?", a: "Yes. The output is a real .docx file with selectable text, paragraphs and basic headings — not a picture of the page." },
      { q: "Does the tool support scanned PDFs?", a: "Not directly. Scanned PDFs are images of text and need OCR first. Born-digital PDFs convert instantly." },
      { q: "Is there a file size limit?", a: "There is no server-side limit because nothing is uploaded. The practical limit is your device's available memory." },
    ],
  },
  {
    slug: "how-to-compress-pdf-without-losing-quality",
    title: "How to Compress PDF Without Losing Quality",
    description: "Learn how to shrink PDF file size for email and uploads while keeping text crisp and images readable.",
    date: "2026-01-15",
    readingTime: "5 min read",
    excerpt: "A 40 MB PDF is too big for most email systems. Here is how to compress it down without making the result look terrible.",
    related: ["compress-pdf", "split-pdf", "merge-pdf"],
    tags: ["PDF", "Compression", "Email"],
    body: p(
      "PDFs grow quickly. A scanned report at 300 DPI can easily reach 40 or 50 MB, which is bigger than most email systems will accept. The fix is compression — but compression done badly produces a blurry mess. This guide explains how to shrink a PDF without ruining it.",
      "## Why PDFs get so big",
      "Three things bloat a PDF: high-resolution images, embedded fonts and duplicate metadata. Scans are the worst offender because every page is a full-resolution photograph. Vector PDFs created from Word or Google Docs are usually small, unless they include a lot of pictures.",
      "## How compression actually works",
      "A good PDF compressor down-samples images to a sensible resolution (typically 150 DPI for screen viewing or 200 DPI for printing), removes thumbnails the original software embedded for previews, strips out unused fonts and rewrites the file structure. Text is left alone because text is already tiny.",
      "## Step-by-step",
      "1. Open the Compress PDF tool on Convertify.\n2. Drop your PDF onto the page.\n3. Pick a compression level — light keeps print quality, medium is best for email, aggressive is best for the smallest possible file.\n4. Compare the before/after size shown on screen and download the result.",
      "## Tips for keeping quality",
      "- For documents that need to be printed, stick to medium compression.\n- For e-mail attachments and Slack uploads, aggressive is fine.\n- If the PDF is huge because of one or two images, consider replacing those images with smaller versions in the source document and re-exporting.",
      "## When to split instead of compress",
      "Sometimes a PDF is so big that even aggressive compression cannot get it under your e-mail limit. In that case, use the Split PDF tool to break it into chapters and send them as separate attachments. The recipient can re-merge them with Convertify if they want a single file.",
      "## Privacy",
      "Convertify compresses PDFs locally in your browser. That matters when you are compressing a contract, an invoice or any other document with personal data — none of it ends up on a third-party server.",
      "## Wrap-up",
      "Compressing a PDF is one of those tasks that should take ten seconds. Bookmark the Compress PDF tool, pick a level that matches your use case and stop fighting with bloated attachments.",
    ),
    faqs: [
      { q: "Will compression make my PDF blurry?", a: "Not at the light or medium levels. Aggressive compression visibly softens images but is still readable." },
      { q: "Can I compress a password-protected PDF?", a: "Unlock the PDF first using the Unlock PDF tool, then compress the result." },
    ],
  },
  {
    slug: "best-free-pdf-tools-for-students",
    title: "The Best Free PDF Tools for Students in 2026",
    description: "From merging lecture notes to compressing assignments, these free PDF tools will save students hours every term.",
    date: "2026-01-20",
    readingTime: "7 min read",
    excerpt: "If you are at university, half of your life is PDF. Here are the free tools that actually make studying easier.",
    related: ["merge-pdf", "split-pdf", "compress-pdf", "pdf-to-word"],
    tags: ["Students", "Productivity"],
    body: p(
      "University runs on PDFs. Reading lists, lecture slides, past papers, assignment briefs, signed forms — all PDF. Knowing the right free tools makes the difference between scrambling at 2am and submitting work on time. Here are the tools we recommend, all free, all browser-based, all without sign-up.",
      "## Merge PDF: build the perfect revision pack",
      "Combine all of a module's lecture slides into one searchable PDF you can scroll through during revision. Add the seminar handouts at the end so you have everything in one place.",
      "## Split PDF: extract one chapter from a textbook scan",
      "Got a 600-page textbook scan and only need chapter four? Split PDF lets you keep just the pages you need. Lighter file, faster scrolling, easier to annotate.",
      "## Compress PDF: keep your assignment under the upload limit",
      "Most submission portals cap uploads at 20 MB. Compress PDF keeps your work readable while making the file small enough to upload without an error message at 23:58.",
      "## PDF to Word: edit feedback inline",
      "When a tutor returns a PDF with comments, convert it to Word so you can incorporate the feedback directly into your draft.",
      "## JPG to PDF: turn phone photos into a single document",
      "Snap photos of whiteboard notes, then bundle them into one PDF for your study group.",
      "## Sign PDF: handle forms without printing",
      "Sign accommodation contracts, internship paperwork and module change forms without finding a printer. Convertify lets you draw or upload a signature and place it on any page.",
      "## Why we recommend browser-based tools",
      "Student laptops are usually low on storage and short on RAM. Installing five different PDF apps eats space and slows down the machine. Browser-based tools have zero footprint and update themselves automatically.",
      "## Privacy matters more than you think",
      "Assignment drafts, application forms and ID scans are sensitive. Convertify processes everything locally, so your documents never sit on someone else's server. That is genuinely useful when you are uploading a passport scan for a visa application.",
      "## Wrap-up",
      "Bookmark these tools at the start of term and you will never lose an hour to PDF wrangling again. They are free, they work on phones and they do not need an account.",
    ),
    faqs: [
      { q: "Are these tools really free for students?", a: "Yes. Convertify is free for everyone — students, freelancers, businesses." },
      { q: "Do I need to install anything?", a: "No. Open the page in any modern browser and start working." },
    ],
  },
  {
    slug: "pdf-vs-word-which-format-should-you-use",
    title: "PDF vs Word: Which Format Should You Use?",
    description: "A practical comparison of PDF and Word, with clear advice on when to send which format.",
    date: "2026-01-25",
    readingTime: "6 min read",
    excerpt: "PDF is for sharing finished work. Word is for editing in progress. Here is the longer version of that rule.",
    related: ["pdf-to-word", "word-to-pdf"],
    tags: ["PDF", "Word", "Comparison"],
    body: p(
      "PDF and Word solve different problems. Sending the wrong one wastes everyone's time. This guide breaks down when each format makes sense and what to do when you need to convert between them.",
      "## What PDF is good at",
      "PDF was designed to look the same on every device. Open it on Windows, macOS, Linux, iOS or Android and the layout, fonts and images appear exactly as the author intended. That makes PDF perfect for finished work: contracts, invoices, brochures, CVs, e-books and reports.",
      "PDFs are also harder to change accidentally. A signed contract sent as a PDF is much harder to alter than the same contract sent as a Word document — a useful property when the document needs to be trusted.",
      "## What Word is good at",
      "Word documents are made for editing. Track changes, comments, real-time collaboration in OneDrive or Google Drive, easy reflow when you adjust margins. Send a Word document when you want the recipient to be able to edit it.",
      "Word also handles structural changes better than PDF. Inserting a new section, reordering chapters or applying a different style across the whole document is trivial in Word and painful in PDF.",
      "## When to send each",
      "- Sending a CV to apply for a job → PDF\n- Drafting a CV with a friend → Word\n- Sending an invoice → PDF\n- Drafting a contract template → Word\n- Sharing a report with a wide audience → PDF\n- Co-writing the same report with two colleagues → Word",
      "## Converting between them",
      "Convertify has free, browser-based tools for both directions. PDF to Word turns a finished PDF back into editable text. Word to PDF locks down a draft once it is final. Both run locally, so you do not have to send draft contracts through a third-party server.",
      "## Common mistakes",
      "The most common mistake is sending a PDF when the recipient needs to edit it, then having them retype the whole document. The second most common is sending a Word file as the final version of a contract, then discovering the recipient has changed clauses you did not agree to.",
      "## Wrap-up",
      "PDF for shipping. Word for working. Use Convertify to switch between them when the situation changes.",
    ),
    faqs: [
      { q: "Can I edit a PDF directly?", a: "You can with Convertify's Edit PDF tool, but for serious edits, convert to Word first." },
      { q: "Will Word to PDF preserve fonts?", a: "Yes — common fonts and embedded fonts both come through correctly." },
    ],
  },
  {
    slug: "how-to-merge-pdf-files-online",
    title: "How to Merge PDF Files Online (Free & Private)",
    description: "Combine two or more PDFs into a single, ordered document directly in your browser.",
    date: "2026-02-01",
    readingTime: "5 min read",
    excerpt: "Merging PDFs takes seconds when the tool is right. Here is the simple, private way to do it.",
    related: ["merge-pdf", "split-pdf", "compress-pdf"],
    tags: ["PDF", "Merge", "Tutorial"],
    body: p(
      "Combining several PDFs into one tidy document is one of the most common file-handling tasks at work and at home. This guide walks through the simplest way to do it without installing anything or uploading sensitive files to a stranger's server.",
      "## When you need to merge PDFs",
      "Common scenarios include: combining a CV, cover letter and portfolio into one application document; stitching scanned contract pages together after signing; bundling monthly bank statements into a year-end PDF for tax filing; or assembling a report from chapters that were written separately.",
      "## Step-by-step",
      "1. Open Convertify's Merge PDF tool.\n2. Drag your PDFs onto the upload area, or tap to choose them.\n3. Drag the file thumbnails to put them in the right order.\n4. Click Merge — your browser combines the files locally.\n5. Download the single, merged PDF.",
      "## Why local processing matters",
      "Most merge tools upload your files to a server. That is fine for harmless documents, but a problem for contracts, payslips or anything containing personal information. Convertify never uploads — your files are read into the browser, merged with pdf-lib and saved straight back to your downloads folder.",
      "## Tips",
      "- If your output is huge, run it through Compress PDF afterwards.\n- If you accidentally merged the wrong file, use Split PDF to extract just the pages you need.\n- Merging works for any number of files, but very large batches may run out of browser memory on older phones.",
      "## Wrap-up",
      "Merging PDFs is a five-second job with the right tool. Bookmark Merge PDF, drop your files in and download the result. No sign-up, no watermark, no upload.",
    ),
    faqs: [
      { q: "Is there a limit on number of PDFs I can merge?", a: "There is no hard limit. Practical limits depend on your device's memory." },
      { q: "Will the merged PDF look the same as the originals?", a: "Yes. Pages are copied exactly, with their fonts and images preserved." },
    ],
  },
  {
    slug: "how-to-split-large-pdf-files",
    title: "How to Split Large PDF Files (Pages, Ranges, Chunks)",
    description: "Break a big PDF into smaller files by single pages, custom ranges or fixed-size chunks.",
    date: "2026-02-05",
    readingTime: "5 min read",
    excerpt: "Splitting a PDF is the fastest way to share just the pages you actually need.",
    related: ["split-pdf", "merge-pdf", "compress-pdf"],
    tags: ["PDF", "Split", "Tutorial"],
    body: p(
      "Splitting a PDF is the mirror image of merging. Instead of combining files, you take one big file and break it into smaller pieces. The reasons are practical: e-mail size limits, sharing only the relevant chapter or extracting a single page for a form.",
      "## Three ways to split",
      "There are three patterns for splitting a PDF, and a good tool supports all of them: extract a single page, extract a custom range like 5–12, or break the file into fixed-size chunks like every 10 pages. Convertify's Split PDF supports all three.",
      "## Step-by-step",
      "1. Open the Split PDF tool.\n2. Drop in your PDF.\n3. Pick the pages or ranges you want to extract.\n4. Click Split. The browser produces one or more new PDFs.\n5. Download each output, or download a ZIP if there are many.",
      "## Combine with other tools",
      "Splitting often comes before another step. Split a document into chapters and run each through Compress PDF for a tiny e-mail-friendly version. Split, edit one page in Edit PDF, then merge the result back together.",
      "## Privacy",
      "Like every Convertify tool, Split PDF runs locally. Your big confidential PDF never leaves your device — even if the device is a phone on a cafe Wi-Fi network.",
      "## Wrap-up",
      "Splitting a PDF should not require an installer or an account. Bookmark Split PDF and stop scrolling through 200-page documents to find the one page you need.",
    ),
    faqs: [
      { q: "Can I extract just one page?", a: "Yes — pick a single-page range like 7-7." },
      { q: "Will quality drop?", a: "No. Pages are copied exactly, not re-rendered." },
    ],
  },
  {
    slug: "how-to-convert-images-to-pdf",
    title: "How to Convert Images to PDF (JPG, PNG, WebP)",
    description: "Bundle phone photos, screenshots or scans into a single PDF you can share or print.",
    date: "2026-02-10",
    readingTime: "5 min read",
    excerpt: "Photos as separate files are awkward to share. A single PDF is much easier.",
    related: ["jpg-to-pdf", "image-to-pdf", "compress-pdf"],
    tags: ["PDF", "Image", "Tutorial"],
    body: p(
      "Converting images into a PDF turns a folder of separate files into one tidy, shareable document. It is one of the most common requests we see — for receipts, identity documents, scans and screenshots.",
      "## Why convert to PDF",
      "Photos are awkward to share in bulk. Most e-mail clients display them inline, breaking the flow of a long message. A PDF keeps the order intact, fits multiple pictures into a single attachment and makes printing predictable.",
      "## Step-by-step",
      "1. Open Convertify's Image to PDF (or JPG to PDF) tool.\n2. Drag your images onto the page — JPG, PNG and WebP all work.\n3. Reorder the thumbnails to control which image becomes which page.\n4. Click Convert and download the resulting PDF.",
      "## Tips",
      "- Crop images first so they fill the page — most tools centre images on a white background, which can look empty.\n- For scans, run the result through Compress PDF if the file is huge.\n- Combine with Merge PDF if you need to add the image-PDF to an existing document.",
      "## Privacy",
      "Image to PDF runs entirely in your browser, which matters when the images are scans of an ID card, payslip or receipt. Nothing is uploaded.",
      "## Wrap-up",
      "If you find yourself emailing four photos as four attachments, stop. Bundle them into a PDF first — it is more professional and easier to read.",
    ),
    faqs: [
      { q: "Can I mix portrait and landscape images?", a: "Yes. Each image becomes its own page sized to fit." },
      { q: "What formats are supported?", a: "JPG, PNG and WebP are the main ones. HEIC and AVIF can be converted to JPG first." },
    ],
  },
  {
    slug: "why-online-pdf-tools-are-useful",
    title: "Why Online PDF Tools Are Useful (and When They Are Not)",
    description: "An honest look at the strengths and limits of browser-based PDF tools versus desktop software.",
    date: "2026-02-15",
    readingTime: "6 min read",
    excerpt: "Online PDF tools have replaced desktop suites for most people. Here is why — and where they still fall short.",
    related: ["merge-pdf", "compress-pdf", "edit-pdf"],
    tags: ["PDF", "Productivity"],
    body: p(
      "Ten years ago, working with PDFs meant buying Adobe Acrobat or installing a free desktop tool. Today, the same jobs are usually done in a browser tab. This article looks at why that shift happened and where it makes sense to stick with desktop software.",
      "## What changed",
      "Modern browsers can do things that used to require a native app. WebAssembly, the Web Crypto API, the Canvas API and libraries like pdf-lib mean that a JavaScript page can read, edit, merge, split, compress and encrypt PDFs without ever uploading them. Convertify is built on exactly this stack.",
      "## Strengths of online tools",
      "- No installation: open a tab and start working\n- Cross-platform: the same site works on Windows, macOS, Linux, iOS and Android\n- Always up to date: no version drift between you and your colleagues\n- Free or low cost: no licence to manage\n- Privacy when implemented well: tools that process locally never see your file",
      "## Where desktop still wins",
      "- Very large batch jobs (hundreds of files at once)\n- Heavy OCR on poor-quality scans\n- Deep print production work with bleeds, spot colours and proofing\n- Air-gapped environments where the browser has no internet at all",
      "## How to choose",
      "For day-to-day work — merging a few PDFs, compressing a report, signing a form, converting to Word — browser tools are the obvious choice. For specialised production workflows, keep a desktop tool around.",
      "## Privacy is the deciding factor",
      "The biggest difference between online tools is whether they upload your file. Some do, some do not. Convertify does not — and you can verify it in your browser's network panel. For sensitive documents, that is the only acceptable option.",
      "## Wrap-up",
      "Online PDF tools are mature, fast and private when built correctly. For 95% of people they have replaced desktop software entirely. The remaining 5% are specialised cases where the desktop still has the edge.",
    ),
    faqs: [
      { q: "Are online PDF tools safe?", a: "They are if they process locally, like Convertify. Tools that upload your file are only as safe as the company running them." },
      { q: "Are they really free?", a: "Convertify is. Some competitors gate features behind paywalls." },
    ],
  },
  {
    slug: "how-to-protect-pdf-files",
    title: "How to Password-Protect a PDF (and Why You Should)",
    description: "A practical guide to encrypting PDFs with a password before you send them.",
    date: "2026-02-20",
    readingTime: "5 min read",
    excerpt: "If you ever email a contract, an invoice or a payslip, you should know how to lock it.",
    related: ["protect-pdf", "unlock-pdf", "sign-pdf"],
    tags: ["PDF", "Security"],
    body: p(
      "Sending a sensitive PDF without a password is the digital equivalent of mailing a contract on the back of a postcard. Anyone with access to the inbox, the forwarded thread or the shared drive can read it. Password protection is the simplest fix.",
      "## When to protect",
      "Always protect: contracts with personal data, payslips, invoices, ID scans, medical records, internal financial reports. Optional: marketing material, public reports, anything you would happily publish on a website.",
      "## Step-by-step",
      "1. Open Convertify's Protect PDF tool.\n2. Drop in your PDF.\n3. Type the password you want recipients to use. Pick something strong — long passphrases beat short complicated ones.\n4. Download the encrypted PDF and share the password through a different channel (text, phone call, password manager).",
      "## Why share the password separately",
      "If you e-mail the file and the password in the same message, anyone reading the e-mail can open the PDF. Sending the password by SMS or via a password manager keeps the two halves apart.",
      "## What protection actually does",
      "Convertify uses strong AES encryption. Without the password, the file is unreadable — not just hidden from the average user, but mathematically inaccessible. That is real protection, not security theatre.",
      "## When you need to unlock",
      "If you have legitimately forgotten the password, or you are the file owner removing protection on a document that no longer needs it, use the Unlock PDF tool. Both Protect and Unlock run locally — your encrypted contracts never leave your device.",
      "## Wrap-up",
      "Password-protecting a PDF takes ten seconds. The next contract you send by email — protect it. Future you will thank present you.",
    ),
    faqs: [
      { q: "Is the encryption strong?", a: "Yes — AES-256, the same standard used to protect government documents." },
      { q: "Can I recover a lost password?", a: "No. That is the point of strong encryption. Store passwords in a password manager." },
    ],
  },
  {
    slug: "how-to-reduce-pdf-file-size-for-email",
    title: "How to Reduce PDF File Size for Email",
    description: "Get your PDF under the 25 MB limit most e-mail systems impose without ruining the quality.",
    date: "2026-02-25",
    readingTime: "5 min read",
    excerpt: "Almost every email system rejects attachments over 25 MB. Here is how to stay under the limit.",
    related: ["compress-pdf", "split-pdf", "merge-pdf"],
    tags: ["PDF", "Email"],
    body: p(
      "Gmail, Outlook and most corporate e-mail systems reject attachments over 25 MB. PDFs full of scanned pages or high-resolution images frequently break that limit. Here are the practical fixes, in order of how aggressively they shrink your file.",
      "## 1. Compress the PDF",
      "The first move is always to compress. Convertify's Compress PDF tool down-samples images, removes redundant metadata and rewrites the file structure. A typical 50 MB scan drops to 8–12 MB without obviously degrading quality.",
      "## 2. Split into smaller files",
      "If compression is not enough, split the PDF into chapters with Split PDF and send them as separate attachments. The recipient can re-merge them with Merge PDF if they want a single file again.",
      "## 3. Use a sharing link instead",
      "For really big files, upload to a cloud drive (Google Drive, Dropbox, OneDrive) and share a link. This is the only realistic option for files over 100 MB, and it works well when the recipient does not need a permanent local copy.",
      "## What to avoid",
      "- Do not zip the PDF. PDFs are already compressed, so zipping rarely shrinks them more than 1–2%.\n- Do not screenshot pages and send the screenshots — quality drops and the file usually grows.\n- Do not pay a one-off fee to a sketchy compression site that uploads your file to who knows where.",
      "## Privacy",
      "Convertify's Compress PDF runs locally, which matters when the file you are shrinking is a confidential client report.",
      "## Wrap-up",
      "Compress first, split if needed, share by link as the last resort. With those three moves you can get any PDF to its destination without hitting the 25 MB wall.",
    ),
    faqs: [
      { q: "How small can compression make a PDF?", a: "Typically 30-70% smaller depending on image content." },
      { q: "Will compression break links inside the PDF?", a: "No — internal links and bookmarks are preserved." },
    ],
  },
];

export const getPost = (slug: string) => BLOG_POSTS.find((p) => p.slug === slug);
