export interface ToolMeta {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  keywords: string[];
  intro: string;
  benefits: string[];
  steps: string[];
  faqs: { q: string; a: string }[];
  related: string[];
}

const baseSteps = (name: string, verb: string) => [
  `Click the upload area or drag your file into the ${name} workspace.`,
  `Adjust the available options to match how you want to ${verb}.`,
  `Press the action button — processing happens instantly inside your browser.`,
  `Download the finished file. Nothing is uploaded to a server.`,
];

const baseBenefits = [
  "100% free with no sign-up, watermarks, or hidden limits.",
  "Files are processed locally in your browser, so your data stays private.",
  "Works on any modern device — desktop, tablet, or mobile.",
  "No software install required. Open the page and start working.",
  "Fast, reliable output you can download immediately.",
];

const commonFaqs = (name: string) => [
  {
    q: `Is ${name} really free?`,
    a: `Yes. ${name} on Convertify is completely free to use, with no daily limits, no watermarks and no account required.`,
  },
  {
    q: `Are my files safe with ${name}?`,
    a: `Your files never leave your device. ${name} runs entirely in your browser, so nothing is uploaded to or stored on our servers.`,
  },
  {
    q: `Does ${name} work on mobile?`,
    a: `Yes. The interface is fully responsive and supports drag-and-drop on desktop and tap-to-upload on mobile devices.`,
  },
  {
    q: `Do I need to install any software?`,
    a: `No. Convertify is a web app — there is nothing to install. Just open the page and use ${name} right away.`,
  },
  {
    q: `What file formats does ${name} support?`,
    a: `It supports the most common formats for the task. The upload area shows the accepted file types when you open the tool.`,
  },
];

const make = (
  slug: string,
  name: string,
  tagline: string,
  verb: string,
  description: string,
  keywords: string[],
  intro: string,
  related: string[],
): ToolMeta => ({
  slug,
  name,
  tagline,
  description,
  keywords,
  intro,
  benefits: baseBenefits,
  steps: baseSteps(name, verb),
  faqs: commonFaqs(name),
  related,
});

export const TOOL_META: Record<string, ToolMeta> = {
  "merge-pdf": make(
    "merge-pdf",
    "Merge PDF",
    "Combine multiple PDFs into one document",
    "merge",
    "Free online tool to merge PDF files into a single document. Combine PDFs in any order, securely in your browser.",
    ["merge pdf free", "combine pdf online", "join pdf files"],
    "Merge PDF lets you combine two or more PDF documents into a single file. It is the fastest way to assemble reports, contracts, scanned pages or chapters into one clean PDF you can share, print or archive — without uploading anything to a server.",
    ["split-pdf", "compress-pdf", "rotate-pdf"],
  ),
  "split-pdf": make(
    "split-pdf",
    "Split PDF",
    "Extract pages or split a PDF into multiple files",
    "split",
    "Split a PDF into separate files or extract specific pages online — free, fast, and private.",
    ["split pdf online", "extract pdf pages", "pdf splitter free"],
    "Split PDF makes it easy to break a large PDF into smaller documents or pull out exactly the pages you need. Useful for sharing single chapters, separating scanned batches or removing unwanted pages.",
    ["merge-pdf", "compress-pdf", "rotate-pdf"],
  ),
  "compress-pdf": make(
    "compress-pdf",
    "Compress PDF",
    "Reduce PDF file size without losing quality",
    "compress",
    "Compress PDF files online for free. Shrink large PDFs for email, upload, and storage while keeping quality.",
    ["compress pdf", "reduce pdf size", "shrink pdf online"],
    "Compress PDF reduces the file size of any PDF so it is easier to email, upload or store. The tool intelligently optimises images and embedded fonts to keep the document looking sharp at a fraction of its original size.",
    ["merge-pdf", "split-pdf", "pdf-to-jpg"],
  ),
  "pdf-to-jpg": make(
    "pdf-to-jpg",
    "PDF to JPG",
    "Convert PDF pages into high-quality JPG images",
    "convert",
    "Turn each page of a PDF into a JPG image online — free, accurate, and instant.",
    ["pdf to jpg", "pdf to image converter", "convert pdf pages to jpg"],
    "PDF to JPG converts every page of your PDF into a sharp JPG image. Perfect for previews, thumbnails, social media or for using PDF content where image files are required.",
    ["jpg-to-pdf", "image-to-pdf", "compress-image"],
  ),
  "jpg-to-pdf": make(
    "jpg-to-pdf",
    "JPG to PDF",
    "Combine JPG images into a single PDF",
    "convert",
    "Convert JPG images into a single PDF document. Reorder, rotate, and export — all online and free.",
    ["jpg to pdf", "image to pdf", "convert jpg to pdf online"],
    "JPG to PDF turns one or more images into a tidy, paginated PDF you can share or print. Drop in your photos, arrange them in the right order and download the finished PDF.",
    ["image-to-pdf", "merge-pdf", "compress-pdf"],
  ),
  "rotate-pdf": make(
    "rotate-pdf",
    "Rotate PDF",
    "Rotate PDF pages to any angle",
    "rotate",
    "Rotate one or all pages of a PDF online — free, instant, and without quality loss.",
    ["rotate pdf", "rotate pdf pages online", "fix pdf orientation"],
    "Rotate PDF lets you fix the orientation of one page, several pages or the whole document. Great for scans that came in sideways or upside down.",
    ["merge-pdf", "split-pdf", "edit-pdf"],
  ),
  "edit-pdf": make(
    "edit-pdf",
    "Edit PDF",
    "Annotate, add text and edit PDF documents",
    "edit",
    "Edit PDF files online — add text, shapes, highlights and annotations directly in your browser.",
    ["edit pdf online", "pdf editor free", "annotate pdf"],
    "Edit PDF gives you a lightweight editor for adding text, notes and shapes to any PDF. Useful for filling forms, signing comments or marking up documents before sending them on.",
    ["sign-pdf", "merge-pdf", "rotate-pdf"],
  ),
  "protect-pdf": make(
    "protect-pdf",
    "Protect PDF",
    "Add a password to secure your PDF",
    "protect",
    "Password-protect any PDF online. Encrypt sensitive documents in your browser — free and secure.",
    ["password protect pdf", "encrypt pdf online", "secure pdf"],
    "Protect PDF locks your document with a password so only people with the password can open it. Ideal for contracts, invoices, IDs and any sensitive paperwork.",
    ["unlock-pdf", "sign-pdf", "edit-pdf"],
  ),
  "unlock-pdf": make(
    "unlock-pdf",
    "Unlock PDF",
    "Remove password protection from a PDF",
    "unlock",
    "Remove the password from a PDF you own — free, fast, and processed entirely in your browser.",
    ["unlock pdf", "remove pdf password", "decrypt pdf online"],
    "Unlock PDF removes the password from PDF files you have permission to access, so you can read, edit or print them without entering a password every time.",
    ["protect-pdf", "edit-pdf", "merge-pdf"],
  ),
  "sign-pdf": make(
    "sign-pdf",
    "Sign PDF",
    "Add your signature to any PDF",
    "sign",
    "Sign PDF documents online — draw, type or upload a signature and place it on any page.",
    ["sign pdf online", "electronic signature pdf", "esign pdf free"],
    "Sign PDF lets you draw or type a signature, place it precisely where you need it and download a signed copy. Great for contracts, agreements and forms.",
    ["edit-pdf", "protect-pdf", "merge-pdf"],
  ),
  "word-to-pdf": make(
    "word-to-pdf",
    "Word to PDF",
    "Convert DOC and DOCX files to PDF",
    "convert",
    "Convert Word documents (DOC, DOCX) to PDF online for free. Preserve fonts, images and layout.",
    ["word to pdf", "docx to pdf", "convert word to pdf online"],
    "Word to PDF turns Microsoft Word documents into clean PDF files that look the same on every device. Ideal for sharing reports, CVs and contracts in a universal format.",
    ["pdf-to-word", "merge-pdf", "compress-pdf"],
  ),
  "pdf-to-word": make(
    "pdf-to-word",
    "PDF to Word",
    "Convert PDF files into editable Word documents",
    "convert",
    "Convert PDF to editable Word (DOCX) online — free, accurate, and works in your browser.",
    ["pdf to word converter free", "convert pdf to editable word online", "pdf to docx"],
    "PDF to Word converts your PDF into an editable .docx file you can open in Microsoft Word, Google Docs or Pages. Perfect for reusing text, updating contracts or repurposing reports.",
    ["word-to-pdf", "edit-pdf", "merge-pdf"],
  ),
  "excel-to-pdf": make(
    "excel-to-pdf",
    "Excel to PDF",
    "Convert XLSX, XLS and CSV spreadsheets to PDF",
    "convert",
    "Convert Excel spreadsheets (XLSX, XLS, CSV) into clean PDF tables online — free, fast, and 100% private.",
    ["excel to pdf", "xlsx to pdf", "csv to pdf", "convert excel to pdf online", "spreadsheet to pdf"],
    "Excel to PDF turns your spreadsheets into clean, paginated PDF tables with selectable text. Each sheet becomes its own section, perfect for sharing reports, invoices and data exports without exposing the raw workbook.",
    ["pdf-to-word", "word-to-pdf", "merge-pdf"],
  ),
  "pdf-to-excel": make(
    "pdf-to-excel",
    "PDF to Excel",
    "Convert PDF tables and documents into editable Excel spreadsheets",
    "convert",
    "Convert PDF files into editable Excel (XLSX) spreadsheets online — free, fast, and 100% private. Each PDF page becomes its own worksheet.",
    ["pdf to excel", "pdf to xlsx", "convert pdf to spreadsheet", "extract tables from pdf", "pdf to excel online"],
    "PDF to Excel extracts text and tables from your PDF and turns them into an editable .xlsx workbook with one sheet per page. Open the result in Microsoft Excel, Google Sheets or Apple Numbers and continue editing right away.",
    ["excel-to-pdf", "pdf-to-word", "merge-pdf"],
  ),
  "image-to-pdf": make(
    "image-to-pdf",
    "Image to PDF",
    "Convert images to a single PDF",
    "convert",
    "Convert images (JPG, PNG, WebP) into a single PDF document online — free and private.",
    ["image to pdf", "convert images to pdf", "photos to pdf"],
    "Image to PDF combines any number of images into one PDF, with each image becoming a page. Great for receipts, scans and photo collections.",
    ["jpg-to-pdf", "compress-pdf", "merge-pdf"],
  ),
  "jpg-to-png": make(
    "jpg-to-png",
    "JPG to PNG",
    "Convert JPG images to PNG format",
    "convert",
    "Convert JPG to PNG online — keep transparency support, sharp edges and lossless quality.",
    ["jpg to png", "convert jpg to png", "jpg to png online"],
    "JPG to PNG converts compressed JPG photos into the lossless PNG format, useful when you need a transparent background or higher edit quality.",
    ["png-to-jpg", "compress-image", "resize-image"],
  ),
  "png-to-jpg": make(
    "png-to-jpg",
    "PNG to JPG",
    "Convert PNG images to JPG format",
    "convert",
    "Convert PNG to JPG online for free. Reduce file size while keeping good visual quality.",
    ["png to jpg", "convert png to jpg", "png to jpeg online"],
    "PNG to JPG converts PNG images to the smaller JPG format, ideal for photos, web use and email attachments.",
    ["jpg-to-png", "compress-image", "resize-image"],
  ),
  "webp-to-jpg": make(
    "webp-to-jpg",
    "WebP to JPG",
    "Convert WebP images to JPG",
    "convert",
    "Convert WebP images to JPG online — perfect for sharing on platforms that don't support WebP.",
    ["webp to jpg", "convert webp to jpg", "webp to jpeg"],
    "WebP to JPG turns modern WebP files into universally supported JPG images so you can use them anywhere.",
    ["png-to-jpg", "compress-image", "resize-image"],
  ),
  "avif-to-jpg": make(
    "avif-to-jpg",
    "AVIF to JPG",
    "Convert AVIF images to JPG",
    "convert",
    "Convert AVIF images to JPG online — fast, free, and works in your browser.",
    ["avif to jpg", "convert avif to jpg", "avif converter"],
    "AVIF to JPG converts the next-generation AVIF format into JPG so you can open the files in any image viewer or editor.",
    ["webp-to-jpg", "png-to-jpg", "compress-image"],
  ),
  "heic-to-jpg": make(
    "heic-to-jpg",
    "HEIC to JPG",
    "Convert iPhone HEIC photos to JPG",
    "convert",
    "Convert HEIC photos from iPhone to JPG online — free, batch-friendly and high quality.",
    ["heic to jpg", "iphone photos to jpg", "convert heic online"],
    "HEIC to JPG converts iPhone HEIC photos into JPG so you can view, edit and share them on Windows, Android and the web.",
    ["webp-to-jpg", "png-to-jpg", "compress-image"],
  ),
  "resize-image": make(
    "resize-image",
    "Resize Image",
    "Resize images to any dimensions",
    "resize",
    "Resize images online to any width and height. Keep aspect ratio and image quality.",
    ["resize image online", "image resizer", "change image size"],
    "Resize Image lets you change the pixel dimensions of any image in seconds. Useful for social media, websites, profile pictures and printing.",
    ["compress-image", "image-upscaler", "rotate-image"],
  ),
  "compress-image": make(
    "compress-image",
    "Compress Image",
    "Reduce image file size",
    "compress",
    "Compress images online to reduce file size while keeping good visual quality. JPG, PNG and WebP supported.",
    ["compress image", "reduce image size", "image compressor online"],
    "Compress Image shrinks JPG, PNG and WebP files for faster websites, smaller emails and easier uploads — without an obvious loss in quality.",
    ["resize-image", "image-upscaler", "rotate-image"],
  ),
  "image-upscaler": make(
    "image-upscaler",
    "Image Upscaler",
    "Upscale images to HD or 4K",
    "upscale",
    "Upscale images to higher resolution online — sharpen and enlarge photos for print and HD displays.",
    ["image upscaler", "upscale image to 4k", "enlarge image online"],
    "Image Upscaler enlarges photos to higher resolutions while keeping details crisp. Great for printing, presentations and old low-resolution images.",
    ["resize-image", "compress-image", "rotate-image"],
  ),
  "rotate-image": make(
    "rotate-image",
    "Rotate Image",
    "Rotate images to any angle",
    "rotate",
    "Rotate images online by 90°, 180°, or any custom angle. Free, fast and private.",
    ["rotate image online", "image rotator", "flip image"],
    "Rotate Image lets you turn photos to the correct orientation in one click — handy for scans, phone shots and screenshots.",
    ["resize-image", "compress-image", "image-upscaler"],
  ),
};

export const getToolMeta = (slug: string): ToolMeta | undefined => TOOL_META[slug];
